package irl.server.data;

// Generated 1 févr. 2009 20:54:53 by Hibernate Tools 3.2.4.CR1

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	private Long emailId;
	private User user;
	private String email;
	private String password;

	public Email() {
	}

	public Email(User user, String email, String password) {
		this.user = user;
		this.email = email;
		this.password = password;
	}

	public Long getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Long emailId) {
		this.emailId = emailId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
